USE DbPratice
ALTER TABLE BaoHiem
ADD FOREIGN KEY (BaoHiem_Xe) REFERENCES Xe(Ma);

ALTER TABLE DangKiem
ADD FOREIGN KEY (DangKiem_Xe) REFERENCES Xe(Ma);

ALTER TABLE DKDuongBo
ADD FOREIGN KEY (DKDuongBo_Xe) REFERENCES Xe(Ma);

ALTER TABLE LoTrinh
ADD FOREIGN KEY (LoTrinh_Xe) REFERENCES Xe(Ma);

ALTER TABLE ThanhLy
ADD FOREIGN KEY (ThanhLy_Xe) REFERENCES Xe(Ma);

ALTER TABLE ThongBao
ADD FOREIGN KEY (ThongBao_Xe) REFERENCES Xe(Ma);

ALTER TABLE Xe
ADD FOREIGN KEY ([Xe_LoaiXe]) REFERENCES LoaiXe(Ma);
ALTER TABLE Xe
ADD FOREIGN KEY (Xe_PhieuDKDuongBo) REFERENCES DKDuongBo(Ma);
ALTER TABLE Xe
ADD FOREIGN KEY (Xe_PhieuDangKiem) REFERENCES DangKiem(Ma);
ALTER TABLE Xe
ADD FOREIGN KEY (Xe_BaoHiem) REFERENCES BaoHiem(Ma);